
init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\mk90btl
shallow_clone: true

matrix:
  fast_finish: false

configuration:
  - Debug
  - Release
#  - Product

environment:
  matrix:
    - toolchain: msvc15
      platform: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PROJECTFILE: MK90BTL-VS2015.sln
      
build:
  project: emulator\$(PROJECTFILE)
