
init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\mk90btl
shallow_clone: true

matrix:
  fast_finish: false

configuration:
  - Debug
  - Release
#  - Product

environment:
  matrix:
    - toolchain: msvc13
      project_name: emulator\MK90BTL-VS2013.sln
      platform: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

build:
  project: $(project_name)
